env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "require-jsdoc": "off",
  "react/react-in-jsx-scope": "off",
  "react/prop-types": "off",
  "react/jsx-one-expression-per-line": "off",
  "react/jsx-props-no-spreading": "off",
  "object-curly-newline": "off"
}
